### ISSUE TITLE
Number of Students

### ISSUE THREAD

**Issue by thankgodr** [thankgodr/capstone-js-project#21]
We are two students working on this [project](https://github.com/thankgodr/capstone-js-project/projects/1).

The team's members includes:

1.  @thankgodr 
2. @momotsow

**Comment by aimalamiri** [comment]
Hi @thankgodr, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Untitled](https://user-images.githubusercontent.com/34779928/191327241-37f74da6-10dd-4744-b917-f93ab416cae3.png)

## Invalid Code Review Request

You have submitted a project, that has no information about the team members, please make sure to add your team members and ask for another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by andgarzonmal** [comment]
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi Team   ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### 💯  Highlights 💯
- Good job building the kanban board ✔️

### ♻️ Request changes ♻️

- [x] _Check the comments ._

- [ ] Kindly remember all tasks should have at least one person assigned to them. Group tasks have no responsible assigned.

![image](https://user-images.githubusercontent.com/95243996/203142070-2e52a4fd-9e25-4bdb-869a-406eb22adcbf.png)


___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

## Hi team 👋, 

You have done an excellent job implementing all the required changes 👏 
This milestone is complete!  There is nothing else to say other than... it's time to start building your project :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
